### PR TITLE
Add support for AMD script loaders

### PR DESCRIPTION
**Pull request by conradz**
This change adds support for [AMD](https://github.com/amdjs/amdjs-api/wiki) script loaders. It will detect if there is an AMD loader and will call `define` if there is. You can still load the script using regular script tags also.

### CODE REVIEW

**Comment by csnover** [comment]
I’m not sure what the benefit of this patch is since all competent AMD loaders can also load plain JavaScript files, and this script always modifies the global Date object so is not self-encapsulated nor particularly portable. Could you please explain the circumstances under which you would require this to register explicitly with an AMD loader?

**Comment by conradz** [comment]
This would allow the [enforceDefine](http://requirejs.org/docs/api.html#config-enforceDefine) option to be used without using the [shim](http://requirejs.org/docs/api.html#config-shim) configuration. This allows better catching of [IE script load errors](http://requirejs.org/docs/api.html#ieloadfail). While I can use the shim configuration, this change is extremely small and makes it a little easier to use with RequireJS.

Even though it is not self-encapsulated, RequireJS does provide a nice way to load the module, much like it can load jQuery plugins even though they do not export data through RequireJS and they modify the global `jQuery` object.

**Comment by csnover** [comment]
I’m not seeing why you need to catch load errors in IE like that. Could you please explain why this matters?

P.S. enforceDefine and shim are RequireJS-specific, not part of the AMD spec. I don’t particularly feel like adding more code to this very simple shim just to make it easier for one module loader to detect and report errors in one browser (a browser that you shouldn’t be doing principal development in anyway). I’m not opposed to registering but I need a more compelling reason than this.

**Comment by conradz** [comment]
First of all, this change is not RequireJS-specific; it currently does work in RequireJS. My configuration is RequireJS-specific, since I'm using RequireJS. I'm dynamically loading scripts at runtime in the browser so I don't have a huge initial page load. It only loads the files as the user uses different parts of the application. The reason is a long one, but basically it will use some default code if the specified file doesn't exist. Because of this, I need to make sure to catch the script loading errors to use the default code.

Like I said, this basically just makes life easier for developing with AMD script loaders. Yes, it can work in good script loaders currently, but the preferred way is for scripts to call `define` to signal that they are loaded. And no, I do not use IE for most of my development work, it's just that it should run in recent versions.

**Comment by csnover** [comment]
You’re loading this script using an AMD loader without building it for production?

**Comment by conradz** [comment]
No, the scripts are all optimized using the RequireJS optimizer. Some are just not inlined into the main JS file, and are loaded at runtime. This lets us have a fast initial load time and keep data size down. It then loads the separate JS files when it requires them.

**Comment by csnover** [comment]
Then I’m not sure why it matters that this is not wrapped in a define. After a build, RequireJS adds define calls for all the modules in the built output, including scripts that are not AMD modules.

If you want AMD-based date/time parsing and formatting modules, look to Dojo.

**Pull request closed without merging**
