### PR TITLE
updated lax parser to allow 1 or 2 digit millisecond components

### PR DESCRIPTION
**Pull request by willholley**
New pull request now targeting to the correct branch.

### CODE REVIEW

**Comment by tlianza** [comment]
Thanks!  I don't know if you ran into this for the same reason I did, but I also opened a bug with the JSON.Net library to reliably produce 3-second millisecond components: http://json.codeplex.com/workitem/22869

**Comment by csnover** [comment]
Thanks! @willholley if you have a moment could you please sign a CLA at http://dojofoundation.org/about/claForm#esign?

**Comment by willholley** [comment]
Yes, we are using JSON.NET as well and ran into this issue.

On 11 June 2012 00:43, Tom Lianza
reply@reply.github.com
wrote:

**Comment by willholley** [comment]
Hi Colin,

I've signed the CLA as requested.

Will

On 11 June 2012 05:34, Colin Snover
reply@reply.github.com
wrote:

**Pull request merged**
